import "./globals.css";
import ConfigureAmplifyClientSide from "@/app/amplify-cognito-config";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto">
        <ConfigureAmplifyClientSide></ConfigureAmplifyClientSide>
        {/* ^ running Amplify on the client-side */}
        {children}
      </body>
    </html>
  );
}

// tailwind container: https://tailwindcss.com/docs/container#using-the-container
